[versions]

kotlin = "2.0.20"
kotlinx = "1.9.0-RC.2"
paper = "1.21.1-R0.1-SNAPSHOT"
mccoroutine = "2.19.0"
shadow = "8.3.0"

[libraries]

# Gradle plugins

plugin-kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
plugin-nyaadanbou-conventions = { group = "cc.mewcraft.gradle", name = "conventions", version = "1.0-SNAPSHOT" }
plugin-shadow = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }

# Code dependencies

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx" }
mccoroutine-bukkit-core = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-core", version.ref = "mccoroutine" }
mccoroutine-bukkit-api = { group = "com.github.shynixn.mccoroutine", name = "mccoroutine-bukkit-api", version.ref = "mccoroutine" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
playtime-paper = { group = "cc.mewcraft.playtime", name = "paper", version = "1.0.0-SNAPSHOT" }

[plugins]

pluginyml-paper = { id = "net.minecrell.plugin-yml.paper", version = "0.6.0" }